### Query
GET http://localhost:8086/api/course-documents/1

### Query search
GET http://localhost:8086/api/course-documents?word=mattis

### Elastic
GET http://localhost:9200/courses/_search?pretty=true