name: course-bs

volumes:
  postgres_data:

services:
  db:
    image: postgres:15.7-alpine
    environment:
      TZ: Europe/Budapest
      POSTGRES_DB: course
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "5"
    ports:
      - "5434:5432"