server:
  port: 8085
spring:
  application:
    name: mentorinig-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: course-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/courses,/api/courses/*
          - id: course-query-service
            uri: http://localhost:8086
            predicates:
              - Path=/api/course-documents,/api/course-documents/*